# I. NumPy.

**Оцінювання даної роботи буде ураховувати якість Вашого коду та текстових відповідей. При наявності ЛИШЕ коду , робота оцінюватися НЕ БУДЕ.**  

**Оформлення текстових відповідей повинно проводитися в текстових комірках ноутбука з використанням синтаксису [LaTeX](https://en.wikibooks.org/wiki/LaTeX/Basics) для оформлення тексту та формул.**

**Роботи ідентифіковані як ІДЕНТИЧНІ одразу отримують 0 балів.**

**При реалізації завдань потрібно використовувати методи з бібліотеки numpy та pandas.**

**Рішення з циклами будуть оцінені в 0 балів.**

0. Імпортувати numpy загальноприйнятим способом.

In [47]:
import numpy as np

1. Визначити список з оцінками студента(ки) за семестр. Використовуючи його,

*   Новый пункт
*   Новый пункт

створити одновимірний масив numpy.

In [48]:
grades_list = [85, 92, 78, 95, 88, 75, 90]
grades_array = np.array(grades_list)
print(grades_array)

[85 92 78 95 88 75 90]


[85 92 78 95 88 75 90]

2. Визначити список зі списками, де кожен рядок списку формально означає магазин, а кожна колонка - певний продукт (батон, яйця першої категорії, молоко та ковбаса), а елементами на пересічі є ціни на ці продукти відповідно. Використовуючи цей список, створити матрицю (двовимірний масив) numpy.

In [49]:
prices = np.array([
    [10.0, 20.0, 30.0, 40.0],
    [15.0, 25.0, 35.0, 45.0],
    [26.0, 36.0, 46.0, 57.0],
])
print(prices)

[[10. 20. 30. 40.]
 [15. 25. 35. 45.]
 [26. 36. 46. 57.]]


[[10. 20. 30. 40.]
 [15. 25. 35. 45.]
 [26. 36. 46. 57.]]

3. Отримайте тип даних значень з масивів завдань 2 та 3. Виведіть їх на екран.

In [50]:
print(grades_array.dtype, prices.dtype)

int64 float64


int64 float64

4. Отримайте форми (кортеж з кількістю рядків та колонок) масивів завдань 2 та 3. Виведіть їх на екран.

In [3]:
import numpy as np
grades_list = [85, 92, 78, 95, 88, 75, 90]
grades_array = np.array(grades_list)
prices = np.array([
    [10.0, 20.0, 30.0, 40.0],
    [15.0, 25.0, 35.0, 45.0],
    [26.0, 36.0, 46.0, 57.0],
])
print(grades_array.shape, prices.shape)

(7,) (3, 4)


(7,) (3, 4)

5. Створіть одновимірний масив за допомогою спеціальної функції numpy, який би відображав динаміку стабільно зростаючого (з рівними проміжками) прибутку з продажів  за тиждень, де у перший день не було продажів, а в останній день тижня вдалося заробити 1000 грн 50 коп.

In [52]:
profit = np.linspace(0, 1000.50, 7)
print(profit)

[   0.    166.75  333.5   500.25  667.    833.75 1000.5 ]


[   0.    166.75  333.5   500.25  667.    833.75 1000.5 ]

6. Створіть два масиви. Використовуючи їх, продемонструйте відмінність вертикального та горизонтального обʼєднання масивів.

In [53]:
arr1 = np.array([3, 7, 8])
arr2 = np.array([5, 8, 9])

vertical_stack = np.vstack((arr1, arr2))
horizontal_stack = np.hstack((arr1, arr2))

[[3 7 8]
 [5 8 9]]
[3 7 8 5 8 9]

7. Визначити функцію, яка приймає на вході масив і транспонує його. Скористайтесь методом reshape. І не забудьте почати з docstrings.

In [54]:
def transpose_array(arr):
  return arr.reshape(arr.shape[::1])

8. Створіть два масиви. Використовучи ці масиви, продемонструйте 1) операцію по-елементного додавання, 2) операцію по-елементного віднімання, 3) множення масиву на число, 4) операцію по-елементного множення, і 5) матричного множення.

In [55]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * 2)
print(arr1 * arr2)
print(np.dot(arr1, arr2))

[5 7 9]
[-3 -3 -3]
[2 4 6]
[ 4 10 18]
32


[5 7 9]
[-3 -3 -3]
[2 4 6]
[ 4 10 18]
32

9. Створіть двовимірний масив (матрицю) та розрахуйте: 1) мінімальне число, 2) максимальне число, 3) суму чисел, 4) мінімальні числа для кожного рядка, 5) максимальні числа для кожного стовпчика.

In [56]:
matrix = np.random.randint(1, 10, (3, 3))
print(matrix.min(), matrix.max(), matrix.sum())
print(matrix.min(axis=1), matrix.max(axis=0))

1 8 43
[1 2 5] [8 8 6]


1 8 37
[3 1 1] [7 8 5]

10. Створіть матрицю , де деякі елементи повторюються. Знайдіть унікальні значення елементів цієї матриці та їхні частоти.

In [57]:
matrix = np.array([[1, 2, 3, 2, 1], [2, 3, 4, 3, 2], [3, 4, 5, 4, 3]])
unique_values, counts = np.unique(matrix, return_counts=True)
print(unique_values, counts)

[1 2 3 4 5] [2 4 5 3 1]


[1 2 3 4 5] [2 4 5 3 1]

# II. Importing. Creating DF

0. Імпортувати бібліотеку pandas

In [58]:
import pandas as pd

11. Створити тестовий датафрейм зі списку, що містить записи пацієнтів про їхні прізвища, імена, дату народження, масу тіла та наявність медичного страхування. Одне зі значень зробить пустим. Ознайомтесь з типом кожної колонки.

In [59]:
data = {
    "Surname": ["a", "b", "c"],
    "Name": ["Ivan", "Petro", "Sidor"],
    "Birthday": ["1990-01-01", "1985-05-15", "1995-12-31"],
    "Weight": [75.5, 68.2, 80.0],
    "Insurance": [True, False, True]
}
df = pd.DataFrame(data)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Surname    3 non-null      object 
 1   Name       3 non-null      object 
 2   Birthday   3 non-null      object 
 3   Weight     3 non-null      float64
 4   Insurance  3 non-null      bool   
dtypes: bool(1), float64(1), object(3)
memory usage: 231.0+ bytes
None


# III. Reading from file

12. Завантажити файл missile_attacks_daily.csv з [Kaggle](https://www.kaggle.com/datasets/piterfm/massive-missile-attacks-on-ukraine?select=missile_attacks_daily.csv). Ознайомитись з описом датасету. Додати файл до папки поточної сесії colab notebook на панелі ліворуч або на гугл диск (локально до проєкту, якщо працюєте у пайчармі). Зчитати датафрейм з файлу та вивести датафрейм на екран. Зверніть увагу на те, щоб всі колонки відповідали наведеним у описі типам даних.

In [60]:
df_missiles = pd.read_csv("missile_attacks_daily.csv")
print(df_missiles.head(10))

         time_start          time_end           model  \
0  2025-02-02 19:00  2025-02-03 09:00  Shahed-136/131   
1  2025-02-01 21:00  2025-02-02 09:00  Shahed-136/131   
2        2025-02-02        2025-02-02          Молнія   
3        2025-02-02        2025-02-02            ZALA   
4        2025-02-02        2025-02-02        Supercam   
5        2025-02-02        2025-02-02          Lancet   
6  2025-01-31 19:00  2025-02-01 09:00       X-59/X-69   
7  2025-01-31 19:00  2025-02-01 09:00           X-31P   
8  2025-01-31 19:00  2025-02-01 09:00       X-22/X-32   
9  2025-01-31 19:00  2025-02-01 09:00     X-101/X-555   

                                        launch_place   target  carrier  \
0  Primorsko-Akhtarsk and Chauda, Crimea and Kurs...  Ukraine      NaN   
1  Primorsko-Akhtarsk and Kursk oblast and Oryol ...  Ukraine      NaN   
2                                                NaN    south      NaN   
3                                                NaN    south      NaN   
4 

# IV. Data understanding

13. Виведіть на екран перші 10 рядків зчитаного датафрейму.

In [61]:
print(df.head(10))

  Surname   Name    Birthday  Weight  Insurance
0       a   Ivan  1990-01-01    75.5       True
1       b  Petro  1985-05-15    68.2      False
2       c  Sidor  1995-12-31    80.0       True


14. Отримайте інформацію про форму датафрейму.

In [62]:
print(df.shape)

(3, 5)


15. Отримайте дані про кожну колонку з її назвою, типом даних та кількістю непустих значень.

In [63]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Surname    3 non-null      object 
 1   Name       3 non-null      object 
 2   Birthday   3 non-null      object 
 3   Weight     3 non-null      float64
 4   Insurance  3 non-null      bool   
dtypes: bool(1), float64(1), object(3)
memory usage: 231.0+ bytes
None


16. Отримайте статистику для колонок числового типу.

In [64]:
print(df.describe())

          Weight
count   3.000000
mean   74.566667
std     5.955110
min    68.200000
25%    71.850000
50%    75.500000
75%    77.750000
max    80.000000


17. Отримати кількість унікальних значень у кожній колонці. Вивести на екран значення та кількість цих значень у колонці, яка має найменше унікальних значень.

In [65]:
unique_counts = df.nunique()
min_unique_col = unique_counts.idxmin()
min_unique_count = unique_counts[min_unique_col]
print(unique_counts)

Surname      3
Name         3
Birthday     3
Weight       3
Insurance    2
dtype: int64


# V. Data Cleaning

19. Перетворити колонку launched у цілочислену (Int64). Перевірити, чи все пройшло, як очікувалось.

In [66]:
df_missiles = pd.read_csv("missile_attacks_daily.csv")
df_missile = df_missiles["launched"].astype("Int64")
print(df_missile.dtypes)

Int64


20. Видалити колонки, де кількість непустих значень становить менше 30% від загальної кількості записів.

In [67]:
df_missiles = pd.read_csv("missile_attacks_daily.csv")
df_missile = df_missiles.dropna(thresh=0.3*len(df_missile), axis=1)
print(df_missile.shape)

(2079, 8)


21. Очистити датафрейм від дублікатів (дублюючихся рядків) та записів, де атака продовжувалась відʼємну або нульову кількість часу (що фізично неможливо). Не забудьте оновити індекс. Скільки рядків було видалено? Як ви це перевірили у коді?

In [68]:
df_missiles = pd.read_csv("missile_attacks_daily.csv")
before_rows = len(df_missile)
df_missile["time_start"] = pd.to_datetime(df_missile["time_start"], errors="coerce")
df_missile["time_end"] = pd.to_datetime(df_missile["time_end"], errors="coerce")

df_missile["duration"] = (df_missile["time_end"] - df_missile["time_start"]).dt.total_seconds()

df_missile = df_missile.drop_duplicates()

df_missile = df_missile[df_missile["duration"] > 0]
df_missile.reset_index(drop=True, inplace=True)

print(f"Видалено {before_rows - len(df_missile)} рядків")

Видалено 1617 рядків


22. Виведіть на екран всі рядки, де є хоч одне пропущене значення.

In [69]:
print(df_missile[df_missile.isna().any(axis=1)])

             time_start            time_end           model     launch_place  \
2   2025-01-31 19:00:00 2025-02-01 09:00:00       X-59/X-69  Voronezh oblast   
3   2025-01-31 19:00:00 2025-02-01 09:00:00           X-31P        Black Sea   
4   2025-01-31 19:00:00 2025-02-01 09:00:00       X-22/X-32              NaN   
5   2025-01-31 19:00:00 2025-02-01 09:00:00     X-101/X-555              NaN   
53  2025-01-03 12:00:00 2025-01-03 20:00:00       X-59/X-69              NaN   
..                  ...                 ...             ...              ...   
457 2022-10-06 15:00:00 2022-10-06 20:00:00       Mohajer-6              NaN   
458 2022-10-06 09:00:00 2022-10-06 11:30:00  Shahed-136/131              NaN   
459 2022-10-06 09:00:00 2022-10-06 11:30:00       Mohajer-6              NaN   
460 2022-10-02 00:00:00 2022-10-02 02:00:00  Shahed-136/131              NaN   
461 2022-09-29 23:00:00 2022-09-29 23:59:00  Shahed-136/131              NaN   

                               target  